import { Bathroom } from './supabase';

// Mock data for development when Supabase isn't set up yet
export const mockBathrooms: Bathroom[] = [
  {
    id: '1',
    name: 'Starbucks Downtown',
    description: 'Clean single-stall bathroom. Code required - ask barista.',
    latitude: 40.7589,
    longitude: -73.9851,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    created_by: 'mock-user',
    overall_rating: 4.5,
    cleanliness_rating: 5,
    accessibility_rating: 3,
    privacy_rating: 4,
    facilities_rating: 4,
    review_count: 12,
    has_changing_table: false,
    has_accessible: true,
    has_gender_neutral: false,
    has_family_friendly: false,
    has_air_dryer: true,
    has_paper_towels: true,
    has_soap: true,
    has_sanitizer: false,
    has_changing_station: false,
    has_tampons: false,
    requires_purchase: true,
    key_required: false,
  },
  {
    id: '2',
    name: 'Central Park Public Restroom',
    description: 'Near the Bethesda Fountain. Can get crowded on weekends.',
    latitude: 40.7722,
    longitude: -73.9719,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    created_by: 'mock-user',
    overall_rating: 3.2,
    cleanliness_rating: 3,
    accessibility_rating: 4,
    privacy_rating: 2,
    facilities_rating: 3,
    review_count: 45,
    has_changing_table: true,
    has_accessible: true,
    has_gender_neutral: false,
    has_family_friendly: true,
    has_air_dryer: false,
    has_paper_towels: true,
    has_soap: true,
    has_sanitizer: false,
    has_changing_station: true,
    has_tampons: false,
    requires_purchase: false,
    key_required: false,
  },
  {
    id: '3',
    name: 'Grand Central Terminal',
    description: 'Lower level. Well-maintained, multiple stalls.',
    latitude: 40.7527,
    longitude: -73.9772,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    created_by: 'mock-user',
    overall_rating: 4.0,
    cleanliness_rating: 4,
    accessibility_rating: 5,
    privacy_rating: 3,
    facilities_rating: 4,
    review_count: 89,
    has_changing_table: true,
    has_accessible: true,
    has_gender_neutral: false,
    has_family_friendly: true,
    has_air_dryer: true,
    has_paper_towels: true,
    has_soap: true,
    has_sanitizer: true,
    has_changing_station: true,
    has_tampons: true,
    requires_purchase: false,
    key_required: false,
  },
  {
    id: '4',
    name: 'Barnes & Noble Union Square',
    description: '4th floor. Quiet and usually clean.',
    latitude: 40.7359,
    longitude: -73.9911,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    created_by: 'mock-user',
    overall_rating: 4.3,
    cleanliness_rating: 4,
    accessibility_rating: 4,
    privacy_rating: 5,
    facilities_rating: 4,
    review_count: 23,
    has_changing_table: false,
    has_accessible: true,
    has_gender_neutral: false,
    has_family_friendly: false,
    has_air_dryer: true,
    has_paper_towels: true,
    has_soap: true,
    has_sanitizer: true,
    has_changing_station: false,
    has_tampons: false,
    requires_purchase: false,
    key_required: false,
  },
];
